spring:
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8088"
  cloud:
    config:
      name: hjy
      profile: prd
management:
  endpoints:
    web:
      exposure:
        include: refresh